dependencies {
    modImplementation("net.blay09.mods:kuma-api-fabric:${kuma_version}")
    modImplementation("net.blay09.mods:balm-fabric:${balm_version}") {
        changing = balm_version.contains("SNAPSHOT")
    }
    modCompileOnly "com.terraformersmc:modmenu:$modmenu_version"
    modCompileOnly "net.blay09.mods:craftingtweaks-fabric:$craftingtweaks_version"

    modCompileOnly "mezz.jei:jei-$jei_minecraft_version-fabric-api:$jei_version"
    if (jei_minecraft_version == minecraft_version) {
        modRuntimeOnly "mezz.jei:jei-$jei_minecraft_version-fabric:$jei_version"
    }
}