dependencies {
    implementation(libs.balmForge) {
        changing = libs.versions.balm.get().endsWith("SNAPSHOT")
    }
    implementation("net.blay09.mods:craftingtweaks-forge:$craftingtweaks_version")

    compileOnly "mezz.jei:jei-$jei_minecraft_version-forge-api:$jei_version"
    if (jei_minecraft_version == minecraft_version) {
        runtimeOnly "mezz.jei:jei-$jei_minecraft_version-forge:$jei_version"
    }
}